CREATE TABLE [dbo].[BranchServiceType]
(
	[Id] NVARCHAR(128) NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [NameEn] NVARCHAR(50) NOT NULL, 
    [NameBj] NVARCHAR(50) NOT NULL, 
    [NameDe] NVARCHAR(50) NOT NULL
)
